const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 6202;

app.use(cors());
app.use(express.json());

const mockUser = {
  self: `http://localhost:${PORT}/rest/api/2/user?username=dominik`,
  name: 'dominik',
  emailAddress: 'dominik@example.com',
  displayName: 'Dominik M.',
  active: true,
  timeZone: 'Europe/Berlin',
  avatarUrls: { '48x48': '', '32x32': '', '24x24': '', '16x16': '' },
};

const makeUser = (name, displayName, email) => ({
  self: `http://localhost:${PORT}/rest/api/2/user?username=${name}`,
  name,
  displayName,
  emailAddress: email,
  active: true,
  avatarUrls: { '48x48': '', '32x32': '', '24x24': '', '16x16': '' },
});

const mockIssues = [
  {
    id: '10001',
    key: 'VERS-2847',
    self: `http://localhost:${PORT}/rest/api/2/issue/10001`,
    fields: {
      summary: 'Frontend-Integration: Neues Kunden-Dashboard',
      description: 'Implementierung des neuen Kunden-Dashboards gemäß Figma-Design. Anbindung an die bestehende REST-API für Vertragsdaten.\n\nAkzeptanzkriterien:\n- Dashboard lädt in unter 2 Sekunden\n- Alle Vertragsdaten werden korrekt angezeigt',
      issuetype: { id: '3', name: 'Task', subtask: false },
      project: { id: '10000', key: 'VERS', name: 'Versicherung Frontend' },
      status: {
        id: '3',
        name: 'In Progress',
        statusCategory: { id: 4, key: 'indeterminate', colorName: 'yellow', name: 'In Progress' },
      },
      priority: { id: '2', name: 'High', iconUrl: '' },
      assignee: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      reporter: makeUser('sarah.k', 'Sarah K.', 'sarah@example.com'),
      creator: makeUser('sarah.k', 'Sarah K.', 'sarah@example.com'),
      created: '2026-02-01T09:00:00.000+0100',
      updated: '2026-03-13T09:15:00.000+0100',
      duedate: '2026-03-13',
      resolutiondate: null,
      resolution: null,
      labels: ['frontend', 'dashboard'],
      components: [{ id: '10001', name: 'Frontend', self: '' }],
      fixVersions: [{ id: '10001', name: '2.0.0', released: false, archived: false }],
      environment: null,
      timetracking: {
        originalEstimate: '5d',
        remainingEstimate: '2d',
        timeSpent: '3d',
        originalEstimateSeconds: 144000,
        remainingEstimateSeconds: 57600,
        timeSpentSeconds: 86400,
      },
      comment: {
        startAt: 0, maxResults: 10, total: 1,
        comments: [{
          id: '20001',
          author: makeUser('sarah.k', 'Sarah K.', 'sarah@example.com'),
          body: 'Bitte das Figma-Design nochmal prüfen.',
          created: '2026-03-12T10:00:00.000+0100',
          updated: '2026-03-12T10:00:00.000+0100',
        }],
      },
      attachment: [],
      subtasks: [],
      issuelinks: [],
      parent: null,
      watches: { self: '', watchCount: 1, isWatching: true },
      votes: { self: '', votes: 0, hasVoted: false },
      customfield_10020: { id: 1, name: 'Sprint 42', state: 'active', startDate: '2026-03-07', endDate: '2026-03-20', completeDate: null },
      customfield_10014: null,
      customfield_10016: 5,
    },
  },
  {
    id: '10002',
    key: 'VERS-2801',
    self: `http://localhost:${PORT}/rest/api/2/issue/10002`,
    fields: {
      summary: 'API-Anbindung: Schadensmeldung Formular',
      description: 'REST-API Integration für das Schadensmeldungs-Formular.\n\nEndpoints:\n- POST /api/v2/claims\n- GET /api/v2/claims/{id}/status',
      issuetype: { id: '72', name: 'Story', subtask: false },
      project: { id: '10000', key: 'VERS', name: 'Versicherung Frontend' },
      status: {
        id: '3',
        name: 'In Progress',
        statusCategory: { id: 4, key: 'indeterminate', colorName: 'yellow', name: 'In Progress' },
      },
      priority: { id: '3', name: 'Medium', iconUrl: '' },
      assignee: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      reporter: makeUser('thomas.b', 'Thomas B.', 'thomas@example.com'),
      creator: makeUser('thomas.b', 'Thomas B.', 'thomas@example.com'),
      created: '2026-01-15T14:00:00.000+0100',
      updated: '2026-03-12T16:30:00.000+0100',
      duedate: '2026-03-20',
      resolutiondate: null,
      resolution: null,
      labels: ['api', 'forms'],
      components: [{ id: '10002', name: 'Backend Integration', self: '' }],
      fixVersions: [],
      environment: 'staging',
      timetracking: {
        originalEstimate: '3d',
        remainingEstimate: '1d',
        timeSpent: '2d',
        originalEstimateSeconds: 86400,
        remainingEstimateSeconds: 28800,
        timeSpentSeconds: 57600,
      },
      comment: { startAt: 0, maxResults: 10, total: 0, comments: [] },
      attachment: [],
      subtasks: [],
      issuelinks: [
        {
          id: '30001',
          type: { id: '10000', name: 'Blocks', inward: 'is blocked by', outward: 'blocks' },
          outwardIssue: { id: '10005', key: 'VERS-2823', self: '', fields: { summary: 'Unit Tests: PolicyService Coverage erhöhen', status: { name: 'In Progress' }, priority: { name: 'Medium' }, issuetype: { name: 'Task' } } },
        },
      ],
      parent: null,
      watches: { self: '', watchCount: 2, isWatching: true },
      votes: { self: '', votes: 1, hasVoted: false },
      customfield_10020: { id: 1, name: 'Sprint 42', state: 'active', startDate: '2026-03-07', endDate: '2026-03-20', completeDate: null },
      customfield_10014: 'VERS-2790',
      customfield_10016: 8,
    },
  },
  {
    id: '10003',
    key: 'VERS-2799',
    self: `http://localhost:${PORT}/rest/api/2/issue/10003`,
    fields: {
      summary: 'Bug: Login-Fehler bei SSO-Weiterleitung',
      description: 'Nach dem SSO-Login über Azure AD werden Nutzer nicht korrekt weitergeleitet.\n\nReproduktion:\n1. Session ablaufen lassen\n2. Auf geschützte Seite navigieren\n3. SSO-Login durchführen\n4. → Redirect-Loop tritt auf',
      issuetype: { id: '1', name: 'Bug', subtask: false },
      project: { id: '10000', key: 'VERS', name: 'Versicherung Frontend' },
      status: {
        id: '10001',
        name: 'In Review',
        statusCategory: { id: 4, key: 'indeterminate', colorName: 'yellow', name: 'In Progress' },
      },
      priority: { id: '2', name: 'High', iconUrl: '' },
      assignee: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      reporter: makeUser('anna.l', 'Anna L.', 'anna@example.com'),
      creator: makeUser('anna.l', 'Anna L.', 'anna@example.com'),
      created: '2026-03-05T11:00:00.000+0100',
      updated: '2026-03-13T08:00:00.000+0100',
      duedate: '2026-03-10',
      resolutiondate: null,
      resolution: null,
      labels: ['bug', 'sso', 'auth'],
      components: [{ id: '10003', name: 'Authentication', self: '' }],
      fixVersions: [{ id: '10001', name: '2.0.0', released: false, archived: false }],
      environment: 'production',
      timetracking: {
        originalEstimate: '1d',
        remainingEstimate: '0h',
        timeSpent: '1d',
        originalEstimateSeconds: 28800,
        remainingEstimateSeconds: 0,
        timeSpentSeconds: 28800,
      },
      comment: {
        startAt: 0, maxResults: 10, total: 2,
        comments: [
          {
            id: '20002',
            author: makeUser('anna.l', 'Anna L.', 'anna@example.com'),
            body: 'Reproduziert auf Chrome 122 und Firefox 123.',
            created: '2026-03-06T09:00:00.000+0100',
            updated: '2026-03-06T09:00:00.000+0100',
          },
          {
            id: '20003',
            author: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
            body: 'Fix implementiert, PR erstellt: #415',
            created: '2026-03-13T08:00:00.000+0100',
            updated: '2026-03-13T08:00:00.000+0100',
          },
        ],
      },
      attachment: [
        { id: '40001', filename: 'screenshot-loop.png', size: 145000, mimeType: 'image/png', created: '2026-03-06T09:05:00.000+0100', author: makeUser('anna.l', 'Anna L.', 'anna@example.com') },
      ],
      subtasks: [],
      issuelinks: [],
      parent: null,
      watches: { self: '', watchCount: 4, isWatching: true },
      votes: { self: '', votes: 2, hasVoted: false },
      customfield_10020: { id: 1, name: 'Sprint 42', state: 'active', startDate: '2026-03-07', endDate: '2026-03-20', completeDate: null },
      customfield_10014: null,
      customfield_10016: 2,
    },
  },
  {
    id: '10004',
    key: 'VERS-2756',
    self: `http://localhost:${PORT}/rest/api/2/issue/10004`,
    fields: {
      summary: 'Refactoring: Angular 21 Migration',
      description: 'Schrittweise Migration auf Angular 21.\n\nFortschritt:\n- ✓ Core-Module migriert\n- ✓ Routing auf neue API umgestellt\n- → Komponenten-Migration läuft',
      issuetype: { id: '3', name: 'Task', subtask: false },
      project: { id: '10000', key: 'VERS', name: 'Versicherung Frontend' },
      status: {
        id: '3',
        name: 'In Progress',
        statusCategory: { id: 4, key: 'indeterminate', colorName: 'yellow', name: 'In Progress' },
      },
      priority: { id: '4', name: 'Low', iconUrl: '' },
      assignee: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      reporter: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      creator: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      created: '2026-01-10T10:00:00.000+0100',
      updated: '2026-03-11T14:20:00.000+0100',
      duedate: '2026-04-01',
      resolutiondate: null,
      resolution: null,
      labels: ['refactoring', 'angular', 'migration'],
      components: [{ id: '10001', name: 'Frontend', self: '' }],
      fixVersions: [{ id: '10002', name: '3.0.0', released: false, archived: false }],
      environment: null,
      timetracking: {
        originalEstimate: '10d',
        remainingEstimate: '4d',
        timeSpent: '6d',
        originalEstimateSeconds: 288000,
        remainingEstimateSeconds: 115200,
        timeSpentSeconds: 172800,
      },
      comment: { startAt: 0, maxResults: 10, total: 0, comments: [] },
      attachment: [],
      subtasks: [
        { id: '10041', key: 'VERS-2757', self: '', fields: { summary: 'Migrate AuthModule', status: { name: 'Done' }, priority: { name: 'Low' }, issuetype: { name: 'Sub-task' } } },
        { id: '10042', key: 'VERS-2758', self: '', fields: { summary: 'Migrate SharedModule', status: { name: 'In Progress' }, priority: { name: 'Low' }, issuetype: { name: 'Sub-task' } } },
      ],
      issuelinks: [],
      parent: null,
      watches: { self: '', watchCount: 1, isWatching: true },
      votes: { self: '', votes: 0, hasVoted: false },
      customfield_10020: { id: 2, name: 'Sprint 43', state: 'future', startDate: '2026-03-21', endDate: '2026-04-03', completeDate: null },
      customfield_10014: 'VERS-2700',
      customfield_10016: 13,
    },
  },
  {
    id: '10005',
    key: 'VERS-2823',
    self: `http://localhost:${PORT}/rest/api/2/issue/10005`,
    fields: {
      summary: 'Unit Tests: PolicyService Coverage erhöhen',
      description: 'Test-Coverage für den PolicyService von aktuell 42% auf mindestens 80% erhöhen.',
      issuetype: { id: '3', name: 'Task', subtask: false },
      project: { id: '10000', key: 'VERS', name: 'Versicherung Frontend' },
      status: {
        id: '3',
        name: 'In Progress',
        statusCategory: { id: 4, key: 'indeterminate', colorName: 'yellow', name: 'In Progress' },
      },
      priority: { id: '3', name: 'Medium', iconUrl: '' },
      assignee: makeUser('dominik', 'Dominik M.', 'dominik@example.com'),
      reporter: makeUser('sarah.k', 'Sarah K.', 'sarah@example.com'),
      creator: makeUser('sarah.k', 'Sarah K.', 'sarah@example.com'),
      created: '2026-02-20T09:00:00.000+0100',
      updated: '2026-03-10T11:00:00.000+0100',
      duedate: '2026-03-25',
      resolutiondate: null,
      resolution: null,
      labels: ['testing', 'coverage'],
      components: [{ id: '10004', name: 'Testing', self: '' }],
      fixVersions: [],
      environment: null,
      timetracking: {
        originalEstimate: '2d',
        remainingEstimate: '1d',
        timeSpent: '1d',
        originalEstimateSeconds: 57600,
        remainingEstimateSeconds: 28800,
        timeSpentSeconds: 28800,
      },
      comment: { startAt: 0, maxResults: 10, total: 0, comments: [] },
      attachment: [],
      subtasks: [],
      issuelinks: [],
      parent: null,
      watches: { self: '', watchCount: 1, isWatching: true },
      votes: { self: '', votes: 0, hasVoted: false },
      customfield_10020: { id: 1, name: 'Sprint 42', state: 'active', startDate: '2026-03-07', endDate: '2026-03-20', completeDate: null },
      customfield_10014: null,
      customfield_10016: 3,
    },
  },
];

app.get('/rest/api/2/myself', (_req, res) => {
  res.json(mockUser);
});

app.get('/rest/api/2/search', (_req, res) => {
  res.json({
    startAt: 0,
    maxResults: 50,
    total: mockIssues.length,
    issues: mockIssues,
  });
});

app.listen(PORT, () => {
  console.log(`Mock Jira server running at http://localhost:${PORT}`);
});
